print("Hello World!")
print("Hello Again!")
print("I like typing.")
print("This is fun.")
print("Yay! Printing!")
print("I'd much rather you 'not'")
print('I "said" do not touch this.')
print("Hello World HOw are you doing today")
